language: android

sudo: false

jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.0-beta4"
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.0-beta"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
      - android-sdk-license-.+
      - '.+'


notifications:
  email: false

env:
    - GRADLE_OPTS="-Xmx2048M -XX:MaxPermSize=2048m"

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
#deploy:
#  provider: bintray
#  file: "Path to a descriptor file, containing information for the Bintray upload"
#  user: "Bintray user"
#  key: "Bintray API key"
#  passphrase: "godshala@1Se9"
#  dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"

cache:
  directories:
   - $HOME/.gradle

